import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Details | Food",
    description: "Generated by DCodax",
};

export default function SiteLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
           {children}
        </>
    );
}
