import Footer from "@/components/layout/footer/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Order Details | Food",
    description: "Generated by DCodax",
};

export default function OrderLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            {children}
            <Footer />
        </>
    );
}
