import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "@/lib/fonts";
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/AuthContext";
import BranchSelect from "@/components/ui/BranchSelect";
import BranchPopup from "@/components/popups/BranchPopup";
import RequiredBranchSelectionModal from "@/components/forms/RequiredBranchSelectionModal";

export const metadata: Metadata = {
  title: "Home | Food",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
  <AuthProvider>
    <Toaster position="top-right" richColors />

    {children}
  </AuthProvider>
</body>
    </html>
  );
}