import Footer from "@/components/layout/footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Details | Food",
    description: "Generated by DCodax",
};

export default function CheckoutLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
           {children}
           <Footer />
        </>
    );
}
