import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "@/lib/fonts";
import { Toaster } from "sonner";
import Providers from "@/app/providers";

export const metadata: Metadata = {
  title: "Home | Food",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
  <Providers>
    <Toaster position="top-right" richColors />

    {children}
  </Providers>
</body>
    </html>
  );
}
