import type { Metadata } from "next";
import "../globals.css";
import { poppins } from "@/lib/fonts";
import Navbar from "@/components/layout/navbar/Navbar";

export const metadata: Metadata = {
  title: "Home | Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
